# Generated by Django 5.2.8 on 2025-11-27 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_delete_feederproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('due_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_type', models.CharField(choices=[('customer', 'Customer Due'), ('supplier', 'Supplier Due')], default='customer', max_length=10)),
                ('person_name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('particular', models.CharField(help_text='Description or reason for due', max_length=200)),
                ('total_amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
