# Generated by Django 5.2.8 on 2025-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpurchase',
            name='snf',
            field=models.FloatField(blank=True, help_text='Solid Not Fat percentage', null=True),
        ),
    ]
