# Generated by Django 5.2.8 on 2025-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_mpurchase_snf'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpurchase',
            name='fat',
            field=models.FloatField(blank=True, help_text='Fat percentage', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='fat_per_kg',
            field=models.FloatField(blank=True, help_text='Fat per kg (calculated)', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='fat_rate_per_kg',
            field=models.FloatField(default=7.15, help_text='Fat Rate per kg'),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='rate',
            field=models.FloatField(blank=True, help_text='Rate (fat_per_kg + snf_per_kg)', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='rate_per_ltr',
            field=models.FloatField(blank=True, help_text='Rate per liter (ts + rate)', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='snf_per_kg',
            field=models.FloatField(blank=True, help_text='SNF per kg (calculated)', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='snf_rate_per_kg',
            field=models.FloatField(default=4.55, help_text='SNF Rate per kg'),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='total_solids_per_kg',
            field=models.FloatField(default=10.0, help_text='Total Solids per kg (%)'),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='ts',
            field=models.FloatField(blank=True, help_text='Total Solids', null=True),
        ),
        migrations.AddField(
            model_name='mpurchase',
            name='ts_amount',
            field=models.FloatField(blank=True, help_text='TS Amount (ts * qty)', null=True),
        ),
        migrations.AlterField(
            model_name='mpurchase',
            name='mPurchase_qty',
            field=models.FloatField(help_text='Quantity in Liters'),
        ),
        migrations.AlterField(
            model_name='mpurchase',
            name='mPurchase_rate',
            field=models.FloatField(blank=True, help_text='Legacy rate field', null=True),
        ),
        migrations.AlterField(
            model_name='mpurchase',
            name='mPurchase_total',
            field=models.FloatField(default=0, help_text='Total Amount (rate_per_ltr * qty)'),
        ),
        migrations.AlterField(
            model_name='mpurchase',
            name='snf',
            field=models.FloatField(blank=True, help_text='SNF percentage', null=True),
        ),
    ]
