# Generated by Django 5.2.8 on 2025-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0007_mpurchase_fat_mpurchase_fat_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpurchase',
            name='advance_amount',
            field=models.FloatField(default=0, help_text='Advance amount given to seller in this transaction'),
        ),
    ]
