# Generated by Django 5.2.8 on 2025-12-13 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_mpurchase_advance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=50, unique=True)),
                ('seller_address', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('default_fat_rate_per_kg', models.FloatField(blank=True, default=7.15, help_text='Default Fat Rate per kg', null=True)),
                ('default_snf_rate_per_kg', models.FloatField(blank=True, default=4.55, help_text='Default SNF Rate per kg', null=True)),
                ('default_total_solids_per_kg', models.FloatField(blank=True, default=10.0, help_text='Default Total Solids per kg (%)', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['seller_name'],
            },
        ),
    ]
